#!/bin/bash

WAL_COLORS="$HOME/.cache/wal/colors"
DUNST_CONFIG="$HOME/.config/dunst/dunstrc"

# Extraer color de fondo con # y comillas
BACKGROUND=$(sed -n 1p "$WAL_COLORS")

# Comprobar que contiene #
if [[ "$BACKGROUND" != \#* ]]; then
    echo "Error: color extraído no contiene '#': $BACKGROUND"
    exit 1
fi

# Reemplazar con comillas dobles, el color ya incluye #
sed -i "s/^background = .*/background = \"$BACKGROUND\"/" "$DUNST_CONFIG"
sed -i "s/^frame_color = .*/frame_color = \"$BACKGROUND\"/" "$DUNST_CONFIG"

# Reiniciar dunst
pkill -x dunst
dunst &
